services:
  fb-reels-telegram-bot:
    build: .
    container_name: fb-reels-telegram-bot
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - TZ=Asia/Jakarta
      - SESSION_FILE=/app/data/bot_session.json
      - SESSION_DIR=/app/data/sessions
      - OUTPUT_DIR=/app/data/output
      - TEMP_DIR=/app/data/temp

    volumes:
      - /data/CLI_Mode:/app/data

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
