services:
  fb-reels-telegram-bot:
    build: .
    container_name: fb-reels-telegram-bot
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - TZ=Asia/Jakarta
      - SESSION_FILE=/app/CLI_Mode/bot_session.json
      - OUTPUT_DIR=/app/CLI_Mode/output

    volumes:
      - /data/CLI_Mode:/app/CLI_Mode

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"